### ISSUE TITLE
Module loader support

### ISSUE THREAD

**Issue by winek** [Thelleo/WoE.View.js#1]
Where is support for [AMD and CommonJS](http://addyosmani.com/writing-modular-js/)?

**Comment by Comandeer** [comment]
+1

**Comment by Thelleo** [comment]
There's no support for them, because I can't say, that JS is my specialty and I just didn't know I should use AMD. I have to study how AMD works and then I'll implement support for it.

**Comment by Thelleo** [comment]
Library has been changed into AMD modules. From now it requires using loader like require.js.
