### ISSUE TITLE
Auto-escape of view variables

### ISSUE THREAD

**Issue by winek** [Thelleo/WoE.View.js#2]
The template engine should automagically escape variables in order to prevent XSS attacks.

**Comment by Thelleo** [comment]
Added XSS protection.
param `WoE.View.XSSprotection` (default true) - is protection enabled
param `WoE.View.protectionExcludedVariables` (default []) - variables excluded from protection
method `WoE.View.setXSSprotection(boolean protect)` - setter for WoE.View.XSSprotection
method `WoE.View.excludeFromProtection(string key)` - adds variable to protection-excluded list
method `WoE.View.escapeHTML(string key)` - helper for escaping HMTL
